### ISSUE TITLE
Exception in thread "AWT-EventQueue-0"

### ISSUE THREAD

**Issue by kuzetsa** [MauveCloud/Ic2ExpReactorPlanner#16]
### this is on v2.1.4 ###

**Build from:**

* https://github.com/MauveCloud/Ic2ExpReactorPlanner/releases/tag/v2.1.4
* 253 KB (259,115 bytes)
* CRC32: D48E0DF6
* MD5: 1874F6DC47CADB3F7E0F9E8DCBE1887E
* SHA-1: 05A1B467EA6E07EB7FF58B42CB8B89C6906A0C54

#### Doesn't even seem to work at all: ####

```
C:\Clever_Minecraft_Things\IndustrialCraft REACTOR!!!>java -version

java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)


C:\Clever_Minecraft_Things\IndustrialCraft REACTOR!!!>java -jar Ic2ExpReactorPlanner.jar

Exception in thread "AWT-EventQueue-0" java.util.MissingResourceException: Can't
 find bundle for base name Ic2ExpReactorPlanner/Bundle, locale en_US
        at java.util.ResourceBundle.throwMissingResourceException(Unknown Source)
        at java.util.ResourceBundle.getBundleImpl(Unknown Source)
        at java.util.ResourceBundle.getBundle(Unknown Source)
        at Ic2ExpReactorPlanner.ReactorPlannerFrame.initComponents(ReactorPlannerFrame.java:327)
        at Ic2ExpReactorPlanner.ReactorPlannerFrame.<init>(ReactorPlannerFrame.java:63)
        at Ic2ExpReactorPlanner.ReactorPlannerFrame$16.run(ReactorPlannerFrame.java:1113)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by MauveCloud** [comment]
I did some experimentation, and this seems to be a bizarre bug with the Windows JVM rather than with my planner, because the above error only happens when the planner is in a folder ending with an exclamation point.  When the folder ends with a semicolon, double-clicking the jar fails, but running it from command-line works.  With any other valid punctuation (or just an alphanumeric character) at the end of the folder name, the planner apparently runs fine.

**Comment by kuzetsa** [comment]
Thanks, I hadn't realized this bug even exists this is the first time I experienced it haha.

Renaming the directory actually fixed the issue.
